[build]
builder = "NIXPACKS"
watchPatterns = ["**/*.js", "package.json", "package-lock.json", "migrations/**/*.sql"]

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/api/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

